[build]
builder = "nixpacks"

[build.nixpacksPlan.variables]
NIXPACKS_NODE_VERSION = "22"

[deploy]
startCommand = "node --enable-source-maps dist/index.js"
healthcheckPath = "/xrpc/_health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
